### ISSUE TITLE
Likely collision in validate examples CI job that uses a single MVG API token

### ISSUE THREAD

**Issue by vnadhan** [vikinganalytics/mvg#140]

**Comment by vnadhan** [comment]
@tuix GitHub actions provides job-level concurrency, but there is a caveat. Only two instances of the same job can be alive (`pending` and `in-progress`). If a third instance of the same job is initiated (new PR or MR), the earlier pending job will be cancelled and this new job will assigned the status `pending`. You can read more about it here - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idconcurrency

Another disad of job-level concurrency is that the duration of the pipeline will lengthen due to the pending jobs. This will likely deplete our GitHub Actions run limit. 

I was thinking that why don't we spin an instance of vibium-cloud in the pipeline and run the notebooks against this instance?

**Comment by tuix** [comment]
`papermill` allows parametarization of a notebook by adding a `parameters` tag to a cell. It injects a cell after that cell automatically to override specific parameters. We can override `ENDPOINT` variable using this method in the CI flow.

**Comment by tuix** [comment]
the injection happens when we test the notebooks in the CI workflow. we don't use result of that as the source for documentation so there is no problem in that aspect
