### ISSUE TITLE
update docker images for MVG

### ISSUE THREAD

**Issue by tuix** [vikinganalytics/mvg#168]
Use the API images from AWS

**Comment by vnadhan** [comment]
https://github.com/vikinganalytics/mvg/blob/fa2a80b01bbb59e0bc6abcbc7d7479c3025838fe/mvg/mvg.py#L59-L60
@tuix We just have to update the `tested_api_version` to [0.4.3](https://github.com/vikinganalytics/vibium-cloud/releases/tag/v0.4.3) to use the latest docker image. Am I right?
