### ISSUE TITLE
MVG: Retrying request with status_code None

### ISSUE THREAD

**Issue by vnadhan** [vikinganalytics/mvg#203]
Many a times, different methods in MVG retries calls to the API when it encounters a Bad Gateway. On some retries, the retry message has the word `None`.

**Comment by zanpak** [comment]
We have not seen it appear again after the fixes in uvicorn keep alive property. 

Raman will review the last few days to confirm.

**Comment by pro100watt** [comment]
This is the 502 error logs chart from AWS ALB:
![image](https://user-images.githubusercontent.com/4946529/230304164-45cc770d-5ddc-4ef2-92f4-2e4d7bfbcdf1.png)
We didn't have errors since March 29, so the issue can be closed.
