### ISSUE TITLE
rerun examples after mode color update

### ISSUE THREAD

**Issue by tuix** [vikinganalytics/mvg#68]
after updating the color of modes (see #67) examples need to be rerun to reflect the new colors. 

also changes in #62 affects the examples

**Comment by OskarLiew** [comment]
Update with KPIDemo as well

**Comment by DrFlink** [comment]
Also, there is an error concerning the token in the Error handling chapter.
The token is not reset from being invalid after the [Invalid Token chapter](https://vikinganalytics.github.io/mvg/content/examples/error_handling.html#Invalid-Token) example.
